# Generated by Django 3.2.10 on 2023-08-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230823_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registertb1',
            new_name='registertb',
        ),
    ]
