# Generated by Django 3.2.10 on 2023-08-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_adproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=400)),
                ('passw', models.CharField(max_length=400)),
            ],
        ),
    ]
