# Generated by Django 3.2.10 on 2023-09-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_admin_logins'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.adproduct')),
                ('uids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registertb')),
            ],
        ),
    ]
